### ISSUE TITLE
Feature Request: lint directory

### ISSUE THREAD

**Issue by guyzsarun** [Azure/k8s-lint#47]
### Feature request

Hi, Since usually we have multiple Kubernetes manifest for a project ( Deployment, Service, Configmap ... ) . It would be great if we could also specify a directory of the manifests when linting

Example action.yaml file
```
     - uses: azure/k8s-lint@v1
        with:
          manifests: |
              kubernetes/*
```

```
/home/runner/work/_temp/56c63f42-beac-4e20-8df8-3eee92e0b1d7/kubeval kubernetes/*
ERR  - Could not open file kubernetes/*
```
